version: '3.8'

services:
  web:
    build: .
    container_name: sisvote_web
    command: python manage.py runserver 0.0.0.0:8013
    volumes:
      - .:/app
    ports:
      - "8013:8013"
    env_file:
      - .env
